In [3]:
import os
import pandas as pd
import h5py
import numpy as np

In [13]:
ls

 Volume in drive D is Personal Disk
 Volume Serial Number is CE6F-CB64

 Directory of D:\Projects\Python Notebook

08/28/2024  10:31 PM    <DIR>          .
08/28/2024  10:13 PM    <DIR>          ..
08/28/2024  10:27 PM    <DIR>          .ipynb_checkpoints
08/27/2024  11:16 PM       927,328,158 Bosch_CNC_Machining_Data.zip
08/28/2024  10:31 PM             6,555 Untitled.ipynb
               2 File(s)    927,334,713 bytes
               3 Dir(s)  1,242,788,134,912 bytes free

In [17]:
df = pd.read_csv('CNC Data.csv')

In [18]:
df

,Machine,Timeframe,Process,Example,Label,X_Mean,Y_Mean,Z_Mean,X_Std,Y_Std,Z_Std
0,M01,Aug_2019,OP00,0,good,-3.874870,34.393633,-1014.514865,469.406118,158.931098,142.389925
1,M01,Aug_2019,OP00,1,good,-4.080831,34.439658,-1014.888903,469.336984,156.544283,142.393091
2,M01,Aug_2019,OP00,3,good,-4.016684,32.277508,-1014.742229,469.255084,140.611050,136.813321
3,M01,Aug_2019,OP00,4,good,-4.769266,32.967493,-1015.024702,470.199034,140.766942,142.254450
4,M01,Aug_2019,OP00,5,good,-5.025476,32.631773,-1015.094961,468.322658,143.524050,142.541785
...,...,...,...,...,...,...,...,...,...,...,...
1697,M03,Feb_2020,OP13,12,good,11.519907,21.872776,-1021.095252,407.361520,210.798002,239.066876
1698,M03,Feb_2020,OP13,13,good,11.216271,21.692308,-1021.060111,400.852245,209.811798,236.920096
1699,M03,Feb_2021,OP13,0,good,9.459210,14.617773,-1022.857166,372.030657,182.942854,202.146749
1700,M03,Feb_2021,OP13,1,good,9.564288,17.439919,-1022.401532,372.204986,197.698606,203.164905
1701,M03,Feb_2021,OP13,2,good,9.344506,18.193375,-1022.487604,370.554350,197.698322,209.887536